### ISSUE TITLE
Allow update channels to be updated by configuration

### ISSUE THREAD

**Issue by Drachenkaetzchen** [WildGums/Orc.Squirrel#2]
As I'm not sure if this is a bug or a feature request, I'll include both.

During testing this library, I noticed that when I change the update channels in my project, they don't get persisted in the user's configuration.

For example, in V1 of my App, the stable update channel points to `example.org/stable`. `UpdateService.Initialize<Channel>` calls `UpdateService.InitializeConfigurationKey()` which correctly persists the channel in the user's configuration.

Now I release V2 of my App, where I changed the stable channel to `example.com/releases/stable`. As `UpdateService.InitializeConfigurationKey()` doesn't update the key once it exists in the user's configuration, the old value will remain there forever.

### Expected behaviour

The new channel configuration should be persisted.

### Actual behaviour

The new channel configuration is not persisted.

### Feature description

Possible solutions to the issue above could be:

- Option 1: Add a parameter to `UpdateService.Initialize<Channel>` so that it persists the new channel configuration
- Option 2: Add a property to `UpdateService` to set the behavior of the channel persisting code

I thought about updating the configuration myself, but I'm keen on using the default configuration key names from [Constants.cs](https://github.com/WildGums/Orc.Squirrel/blob/develop/src/Orc.Squirrel/Constants.cs#L28) (aka: No additional developer configuration needed) and additional code to retrieve the key name shouldn't be necessary from a developer's point of view.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting, I will look into your question tomorrow. Sometimes I don't get email notifications, so sorry for my late reply.

**Comment by GeertvanHorrik** [comment]
Just checked the code, InitializeChannel eventually goes into Catel (see https://github.com/Catel/Catel/blob/develop/src/Catel.Core/Configuration/ConfigurationService.cs#L216). A configuration key will only be initialized if it's not already there.

In your case, I would recommend an "upgrade" method at the beginning of your apps to rewrite the config value (GetRoamingValue => if equals to the previous value => upgrade).

Hope this helps!

**Comment by Drachenkaetzchen** [comment]
Well I don't really agree. It should be handled by the library, as it's extremely easy to miss. Also I can't believe that having the first update URL ever seen by the lib is something users and developers would want.

**Comment by GeertvanHorrik** [comment]
What would be a working solution:

1) Without breaking the current behavior
2) Allows customized url configurations

Always overwriting the values would never allow for customizations of the urls?

**Comment by Drachenkaetzchen** [comment]
> What would be a working solution:
> 
> 1. Without breaking the current behavior
> 2. Allows customized url configurations
> 
> Always overwriting the values would never allow for customizations of the urls?

As I wrote in my initial report, I see two options.

* Option 1: Add a parameter to UpdateService.Initialize<Channel> so that it persists the new channel configuration

This makes it immediately visible in the API doc and method parameters that the persist default is false, wouldn't break backwards compatibility. Maybe something like this:

```csharp
/// <summary>
        /// Initializes this instance.
        /// </summary>
        /// <param name="availableChannels">The available channels.</param>
        /// <param name="defaultChannel">The default channel.</param>
        /// <param name="defaultCheckForUpdatesValue">The default value for the check for updates setting.</param>
        /// <param name="overwriteUserConfiguration">true to overwrite the user's configuration with updated channel settings. Defaults to false. </param>

        public void Initialize(IEnumerable<UpdateChannel> availableChannels, UpdateChannel defaultChannel, bool defaultCheckForUpdatesValue, bool overwriteUserConfiguration = false)
````

* Option 2: Add a property to UpdateService to set the behavior of the channel persisting code

This is a bit harder to find, as developers usually don't touch the UpdateService directly. Personally I'd prefer Option 1.


The root cause for this issue was that I copied the code from the LogViewer sample application to get started, just to find that when I updated the URLs, it didn't work. It was not apparent to me why this happened, and only after an hour of digging I realized that the update URLs are actually persisted in the user's app configuration.

If we agree on some kind of solution, and even if it is by documenting the behavior, I'd be more than happy to create a pull request. That's the least I can do for the wonderful set of libraries and especially Orchestra.

**Comment by GeertvanHorrik** [comment]
I think option 1 is doable :-)

Just make sure to create an explicit overload (because adding new parameters, even with default parameters, is a breaking change).

**Comment by Drachenkaetzchen** [comment]
Perfect :) I'm not sure when I find time to create the PR including documentation change, but at least I got it noted in my own product's issue tracker

For reference: https://support.drachenkatze.org/presetmagician/issues/14
